### ISSUE TITLE
CSS: usage of REM, PX etc

### ISSUE THREAD

**Issue by sohilpandya** [FAC10/week1-PAMF#81]
We need to try and be consistent in the usage of `rem` or `px`, we should decide whether we want to go down the route of `rem` or `px` and then follow that pattern throughout the project, at this current moment, you are using both of them interchangeably which is not good practice.

Also at the top level, you've [got the body](https://github.com/FAC10/week1-PAMF/blob/master/css/style.css#L3) 
```css 
body {
  font-family: 'Raleway', sans-serif;
  font-size: 2rem;
  line-height: 1.5;
}
```

The font-size should be in pixels (either 14/16px) at this top level and then you can use `rem` throughout the rest of the CSS. 

The rest of the CSS can then be in `rem` which will be relative to 14/16px.
